# Generated by Django 3.2 on 2021-04-23 16:15

from django.db import migrations
from django.contrib.auth.hashers import make_password

def populate_users(apps, schema_editor):
    User = apps.get_model('catalogue', 'User')
    admin = User(username="admin", password=make_password("admin"), email="admin@catalogue.com", is_superuser=True, is_staff=True)
    admin.save()
    user = User(username="user", password=make_password("catalogue123"), email="user@catalogue.com")
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_users),
    ]
